apiVersion: v1
kind: Service
metadata:
  name: minio-app-service
  namespace: minio-dev
  labels:
    app: minio-app
spec:
  selector:
    app: minio-app
  type: ClusterIP
  ports:
    - name: api
      port: 9000
      targetPort: 9000

    - name: console
      port: 9001
      targetPort: 9001
